car_shop/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path("", include("main.urls", namespace="main")),
    path("admin/", admin.site.urls),
    re_path(r"^nested_admin/", include("nested_admin.urls")),
]

main/urls.py
from django.urls import path

import main.views as main

app_name = "main"

urlpatterns = [
    path("", main.index, name="index"),
    path(
        "create-shop/",
        main.CarShopCreateView.as_view(),
        name="create-shop",
    ),
    path(
        "delete-shop/<pk>/",
        main.CarShopDeleteView.as_view(),
        name="delete-shop",
    ),
    path("edit-shop/<pk>/", main.edit_shop, name="edit-shop"),
    path(
        "shop-details/<pk>/",
        main.CarShopDetailsView.as_view(),
        name="shop-details",
    ),
    path("add-car/<pk>/", main.add_car, name="add-car"),
    path("add-brand/<pk>/", main.add_brand, name="add-brand"),
    path("get-prop-form/", main.get_prop_form, name="get-prop-form"),
]

main/models.py
from django.db import models

# Create your models here.


class OrderableMixin(models.Model):
    """
    Orderable Mixin
    """

    ordering = models.SmallIntegerField(default=0)

    class Meta:
        abstract = True
        ordering = ["ordering"]


class JsonMixin(models.Model):
    """
    Json Mixin
    """

    json = models.JSONField(
        default=dict,
        null=True,
        blank=True,
    )

    class Meta:
        abstract = True


class Company(OrderableMixin):
    """
    Company Model class
    """

    title = models.CharField(max_length=100)
    address = models.CharField(
        max_length=255,
        null=True,
        blank=True,
    )
    email = models.EmailField(
        null=True,
        blank=True,
    )
    phone = models.CharField(
        max_length=100,
        null=True,
        blank=True,
    )

    class Meta:
        verbose_name = "CarShop"

    def __str__(self):
        return self.title

    def get_cars(self):
        if self.cars.select_related().exists():
            return self.cars.select_related()
        return []


class CarBrand(OrderableMixin):
    """
    CarBrand Model class
    """

    title = models.CharField(max_length=255)
    seller = models.ForeignKey(
        Company,
        on_delete=models.CASCADE,
        related_name="brands",
    )

    class Meta:
        verbose_name = "Brand"

    def __str__(self):
        return self.title


class Car(OrderableMixin):
    """
    Car Model class
    """

    title = models.CharField(max_length=255)
    seller = models.ForeignKey(
        Company,
        on_delete=models.CASCADE,
        related_name="cars",
    )
    brand = models.ForeignKey(
        CarBrand,
        on_delete=models.CASCADE,
        related_name="brand_cars",
    )

    def __str__(self):
        return self.title

    def get_props(self):
        if self.props.select_related().exists():
            return self.props.select_related()
        return []


class CarProp(OrderableMixin):
    PROP_SELECT = (
        ("body", "body"),
        ("engine", "engine"),
        ("transmission", "transmission"),
        ("interior", "interior"),
    )
    car = models.ForeignKey(
        Car,
        related_name="props",
        on_delete=models.CASCADE,
    )
    option = models.CharField(max_length=20, choices=PROP_SELECT)
    value = models.CharField(max_length=20)

    class Meta:
        verbose_name = "Property"
        verbose_name_plural = "Properties"

    def __str__(self):
        return f"{self.option}: {self.value}"

main/forms.py
from django import forms

from main.models import Car, CarBrand, CarProp, Company


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        exclude = ("ordering",)


class CarBrandForm(forms.ModelForm):
    class Meta:
        model = CarBrand
        exclude = (
            "ordering",
            "seller",
        )


class CarPropForm(forms.ModelForm):
    class Meta:
        model = CarProp
        exclude = ("car",)


class CarForm(forms.ModelForm):
    class Meta:
        model = Car
        exclude = (
            "ordering",
            "seller",
        )

main/views.py
from django.forms.models import inlineformset_factory
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView
from nested_formset import nestedformset_factory

from main.forms import CarBrandForm, CarForm, CarPropForm, CompanyForm
from main.models import Car, CarProp, Company

# Create your views here.


def index(request):
    title = "Welcome to our CarShops management system!"
    car_shops = Company.objects.all()
    context = {
        "title": title,
        "car_shops": car_shops,
    }
    return render(request, "main/index.html", context)


class CarShopCreateView(CreateView):
    model = Company
    form_class = CompanyForm
    template_name = "main/add_shop.html"

    def get_success_url(self):
        return reverse("main:shop-details", kwargs={"pk": self.object.pk})


def add_brand(request, pk):
    shop = Company.objects.get(pk=pk)
    form = CarBrandForm()
    if request.method == "POST":
        form = CarBrandForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.seller = shop
            instance.save()
            return redirect("main:index")
    context = {
        "form": form,
        "shop": shop,
    }
    return render(request, "main/add_brand.html", context)


def add_car(request, pk):
    form = CarForm()
    shop = Company.objects.get(pk=pk)
    if request.method == "POST":
        props_options = request.POST.getlist("option")
        props_values = request.POST.getlist("value")
        props_forms = [
            CarPropForm({"option": el[0], "value": el[1], "ordering": count})
            for count, el in enumerate(zip(props_options, props_values))
        ]
        form = CarForm(request.POST)
        if form.is_valid():
            car_instance = form.save(commit=False)
            car_instance.seller = shop
            car_instance.save()
            if props_forms and all(f.is_valid() for f in props_forms):
                for f in props_forms:
                    prop_inst = f.save(commit=False)
                    prop_inst.car = car_instance
                    prop_inst.save()
            return redirect("main:shop-details", shop.pk)
    context = {
        "form": form,
        "shop": shop,
    }
    return render(request, "main/add_car.html", context)


def get_prop_form(request):
    context = {"prop_form": CarPropForm}
    return render(request, "main/prop-form.html", context)


def edit_shop(request, pk):
    shop = Company.objects.get(pk=pk)
    form = CompanyForm(instance=shop)
    CarsFormset = nestedformset_factory(
        Company,
        Car,
        nested_formset=inlineformset_factory(
            Car,
            CarProp,
            exclude=("ordering",),
            extra=0,
        ),
        extra=0,
    )
    formset = CarsFormset(instance=shop)
    if request.method == "POST":
        form = CompanyForm(request.POST, instance=shop)
        formset = CarsFormset(request.POST, instance=shop)
        if formset.is_valid() and form.is_valid():
            formset.save()
            form.save()
            return redirect("main:shop-details", shop.pk)
    context = {
        "shop": shop,
        "form": form,
        "formset": formset,
    }
    return render(request, "main/edit_shop.html", context)


class CarShopDetailsView(DetailView):
    model = Company

    def get_template_names(self):
        return ["main/shop-details.html"]


class CarShopDeleteView(DeleteView):
    model = Company
    success_url = reverse_lazy("main:index")
    template_name = "main/confirm_delete.html"

main/templates/main/add_brand.html
<div class="alert bg-info">
  <form action="/add-brand/{{ shop.pk }}/" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-link" type="submit">save</button>
    <a class="btn btn-link" href="{% url 'main:index' %}">dismiss</a>
  </form>
</div>

main/templates/main/add_car.html
<div class="alert bg-info">
  <form action="/add-car/{{ shop.pk }}/" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div id="car-to-{{ shop.pk }}"></div>
    <div class="btn btn-link"
         hx-trigger="click"
         hx-target="#car-to-{{ shop.pk }}"
         hx-swap="beforeend"
         hx-get="/get-prop-form/">+add_prop</div>
    <button class="btn btn-link" type="submit">save</button>
    <a class="btn btn-link" href="{% url 'main:index' %}">dismiss</a>
  </form>
</div>

main/templates/main/add_shop.html
{% extends "main/base.html" %}
{% block content %}
{% include "main/menu.html" %}
<div class="container">
  {% include "main/form_errors.html" %}
  <form action="" method="post">
    <p class="h4">Fill form to add new car shop</p>
    {% csrf_token %}
    <div class="alert bg-light">
      {{ form.as_p }}
    </div>
    <button class="btn btn-light" type="submit">Submit</button>
    <a class="btn btn-link" href="{% url 'main:index' %}">Cancel</a>
  </form>
</div>
{% endblock %}

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{{ title }}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/style.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
              crossorigin="anonymous">
    </head>
    <body>
        {% block content %}{% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/vue@2.7.8/dist/vue.js"></script>
        <script src="https://unpkg.com/htmx.org@1.8.4" integrity="sha384-wg5Y/JwF7VxGk4zLsJEcAojRtlVp1FKKdGy1qN+OMtdq72WRvX/EdRdqg/LOhYeV" crossorigin="anonymous"></script>
    </body>
</html>

main/templates/main/confirm_delete.html
{% extends "main/base.html" %}
{% block content %}
    <div class="container p-5">
        <form method="post" action="">
            {% csrf_token %}
            <p class="alert bg-danger">Are you sure? Delete {{ object.title }}?</p>
            <input type="submit" value="Confirm">
            <a class="btn btn-link" href="{% url 'main:index' %}">Cancel</a>
        </form>
    </div>
{% endblock %}

main/templates/main/edit_shop.html
{% extends "main/base.html" %}
{% block content %}
{% include "main/menu.html" %}
<div class="container">
    <h1>Edit shop: {{ shop.title }}</h1>
    {% if formset.errors %}
      {% for form in formset %}
        {{ form.errors }}
      {% endfor %}
    {% endif %}
    {% if formset.non_field_errors %}<p>Non field errors</p>{% endif %}

    {% if form.errors %}
      <p class="alert bg-danger">{{ form.errors }}</p>
    {% endif %}

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {{ formset.management_form }}
        {% for car in formset %}
            {{ car.nested.management_form }}
            <div class="alert bg-info">
                {{ car.as_p }}
                {% for prop_set in car.nested %}
                  <div class="alert bg-warning">
                    {{ prop_set.as_p }}
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
        <input type="submit" value="Save" />
        <a class="btn btn-link" href="{% url 'main:index' %}">Dismiss</a>
    </form>
</div>
{% endblock %}

main/templates/main/form_errors.html
{% if form.errors %}
    <div class="alert alert-danger">
        Исправьте ошибки формы:
        {% for field in form %}
            {% if field.errors %}{{ field.label_tag }} {{ field.errors }}{% endif %}
        {% endfor %}
    </div>
    {% if form.non_field_errors %}<div class="alert alert-danger">{{ form.non_field_errors }}</div>{% endif %}
{% endif %}

main/templates/main/index.html
{% extends "main/base.html" %}
{% block content %}
    {% include "main/menu.html" %}
    <div class="container">
        {% for car_shop in car_shops %}
            <div class="alert alert-info">
                <p class="h4">{{ car_shop.title }}</p>
                <span class="badge bg-dark">Brands: {{ car_shop.brands.select_related.count }}</span>
                <span class="badge bg-dark">Cars: {{ car_shop.cars.select_related.count }}</span>
                <a class="btn btn-link" href="{% url 'main:shop-details' car_shop.pk %}">details</a>
                <a class="btn btn-link" href="{% url 'main:edit-shop' car_shop.pk %}">edit shop</a>
                <a class="btn btn-link" href="{% url 'main:delete-shop' car_shop.pk %}">del shop</a>
                <a class="btn btn-link" 
                   hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                   hx-post="/add-brand/{{ car_shop.pk }}/"
                   hx-swap="outerHTML"
                   href="{% url 'main:add-brand' car_shop.pk %}">add brand</a>
                <button class="btn btn-link"
                        hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                        hx-post="/add-car/{{ car_shop.pk }}/"
                        hx-swap="outerHTML">add car
                </button>
            </div>
        {% endfor %}
    </div>
{% endblock %}

main/templates/main/menu.html
<div class="container my-2">
    <div class="row">
      <div class="col-sm-3">
          <a class="btn btn-light btn-sm" href="{% url 'main:index' %}">index</a>
        </div>
        <div class="col-sm-3">
            <a class="btn btn-light btn-sm" href="{% url 'main:create-shop' %}">
                add shop
            </a>
        </div>
    </div>
</div>

main/templates/main/prop-form.html
<div class="alert bg-light">
  {{ prop_form.option }} - {{ prop_form.value }}
</div>

main/templates/main/shop-details.html
{% extends "main/base.html" %}
{% block content %}
{% include "main/menu.html" %}

<div class="container py-3">

  <p class="alert bg-info">
      Shop: {{ object.title }}
  </p>

  {% for car in object.get_cars %}
  <p class="alert bg-light">
    <span class="badge bg-dark">{{ car.brand }}</span>
    model title: {{ car.title }}
    <p>Model characteristics:
      <hr>
    </p>
    <ul>
      {% for car_prop in car.get_props %}
      <li>{{ car_prop.option }}: {{ car_prop.value }}</li>
      {% endfor %}
    </ul>
  </p>
  {% endfor %}
</div>

{% endblock %}